OBJECTS	= LRMEXVOL_EN_DVD.iso LRMEXVOL_EN_DVD/sources/install.wim LRMEXVOL_EN_DVD/sources/boot.wim \
LRMCFRE_EN_CD1.iso LRMCFRE_EN_CD2.iso LRMCFRE_EN_DVD.iso LRMCXFRE_EN_DVD.iso LRMEVOL_EN_DVD.iso LRMEXVOL_EN_DVD.iso

LRMEXVOL_EN_DVD.iso : LRMEXVOL_EN_DVD/sources/install.wim LRMEXVOL_EN_DVD/sources/boot.wim
