OBJECTS	:= GRMCNPRFRER_EN_DVD.iso GRMCNPRFRER_EN_DVD/sources/boot.wim GRMCNPRFRER_EN_DVD/sources/install.wim \
GRMCNPRXFRER_EN_DVD.iso GRMCNPRXFRER_EN_DVD/sources/boot.wim GRMCNPRXFRER_EN_DVD/sources/install.wim \
GSP1RMCNENXVOL_EN_DVD.iso GSP1RMCNENXVOL_EN_DVD/sources/boot.wim GSP1RMCNENXVOL_EN_DVD/sources/install.wim \
GSP1RMCNULXFRER_EN_DVD.iso GSP1RMCNULXFRER_EN_DVD/sources/boot.wim GSP1RMCNULXFRER_EN_DVD/sources/install.wim \
GSP1RMCULXFRER_EN_DVD.iso GSP1RMCULXFRER_EN_DVD/sources/boot.wim GSP1RMCULXFRER_EN_DVD/sources/install.wim

GRMCNPRFRER_EN_DVD.iso : GRMCNPRFRER_EN_DVD/sources/boot.wim GRMCNPRFRER_EN_DVD/sources/install.wim
GRMCNPRXFRER_EN_DVD.iso : GRMCNPRXFRER_EN_DVD/sources/boot.wim GRMCNPRXFRER_EN_DVD/sources/install.wim
GSP1RMCNENXVOL_EN_DVD.iso : GSP1RMCNENXVOL_EN_DVD/sources/boot.wim GSP1RMCNENXVOL_EN_DVD/sources/install.wim
GSP1RMCNULXFRER_EN_DVD.iso : GSP1RMCNULXFRER_EN_DVD/sources/boot.wim GSP1RMCNULXFRER_EN_DVD/sources/install.wim
GSP1RMCULXFRER_EN_DVD.iso : GSP1RMCULXFRER_EN_DVD/sources/boot.wim GSP1RMCULXFRER_EN_DVD/sources/install.wim
